---

- name: Disable journald rate-limiting
  lineinfile: "dest=/etc/systemd/journald.conf regexp={{item.regexp}} line='{{item.line}}'"
  with_items:
  - { regexp: "^#RateLimitInterval", line: "RateLimitInterval=0s" }
  - { regexp: "^#RateLimitBurst", line: "RateLimitBurst=0" }
  notify: restart journald

- name: Create journal directory for permanent logs
  file: path=/var/log/journal state=directory
  notify: restart journald

- name: Set journal folder with systemd-tmpfiles
  command: "systemd-tmpfiles --create --prefix /var/log/journal"
  notify: restart journald

- name: As long as Datadog does not support journald on RPM-based linux, we enable rsyslog
  yum: "name={{item}} state=installed"
  with_items:
  - rsyslog
  - rsyslog-gnutls

#- name: Get DataDog certificate for rsyslog
#  get_url: url=https://docs.datadoghq.com/crt/intake.logs.datadoghq.com.crt dest=/etc/ssl/certs/intake.logs.datadoghq.com.crt

- name: Get DataDog certificate for rsyslog
  copy: src=intake.logs.datadoghq.com.crt dest=/etc/ssl/certs/intake.logs.datadoghq.com.crt

- name: Add datadog config to rsyslog
  template: src=datadog.conf.j2 dest=/etc/rsyslog.d/datadog.conf mode=0600
  notify: restart rsyslog

#semanage port -a -t syslog_tls_port_t -p tcp 10516
- name: Enable rsyslog to report to port 10516 in SELinux
  seport: ports=10516 proto=tcp reload=yes setype=syslog_tls_port_t state=present
  notify: restart rsyslog

